name:                langchain-haskell
version:             0.1.0.0
github:              "tusharad/langchain-haskell"
license:             BSD-3-Clause
author:              "tushar"
maintainer:          "tusharadhatrao@gmail.com"
copyright:           "2025 tushar"

extra-source-files:
- README.md
- CHANGELOG.md

description: Build LLM-powered applications in Haskell.

dependencies:
- base >= 4.7 && < 5
- http-conduit
- text
- aeson
- bytestring
- containers
- directory
- pdf-toolbox-document
- ollama-haskell

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  langchain-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - langchain-haskell
