name:                langchain-haskell
version:             0.1.0.0
github:              "tusharad/langchain-haskell"
license:             BSD-3-Clause
author:              "tushar"
maintainer:          "tusharadhatrao@gmail.com"
copyright:           "2025 tushar"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tusharad/langchain-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- http-conduit
- text
- aeson
- bytestring
- ollama-haskell

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  langchain-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - langchain-haskell

tests:
  langchain-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - langchain-haskell
